[package]
name = "piolib-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
pio = "0.3.0"
pio-pi5-rs = {git = "https://github.com/caldwell/pio-pi5-rs.git"}

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"